In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score, confusion_matrix, roc_auc_score, roc_curve
from pandas_profiling import ProfileReport
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("E:\EnsembleLearning_And_RandomForest\EnsembleLearning_And_RandomForest\winequality_red.csv")

In [3]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

## KNN

In [4]:
x = df.drop(columns='quality')

In [5]:
y=df.quality

In [6]:
x

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [7]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=20)

In [9]:
knn1 = KNeighborsClassifier()

In [10]:
knn1.fit(x_train,y_train)

KNeighborsClassifier()

In [11]:
knn1.score(x_test,y_test)

0.5175

In [16]:
pickle.dump(knn1, open('knn1.pkl', 'wb'))

In [17]:
pram = {
    'n_neighbors' : [3,5,7,9,12,13,15,17,21],
    'weights' : ['uniform', 'distance'],
    'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'],
    'leaf_size' : [10, 15 , 20 , 25 , 30 , 35 , 45 , 50],
    'p' : [1,2]
}

In [18]:
grid_knn = GridSearchCV(knn, param_grid=pram)

In [71]:
grid_knn.fit(x_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(n_neighbors=17, weights='distance'),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 15, 20, 25, 30, 35, 45, 50],
                         'n_neighbors': [3, 5, 7, 9, 12, 13, 15, 17, 21],
                         'p': [1, 2], 'weights': ['uniform', 'distance']})

In [72]:
grid_knn.best_params_

{'algorithm': 'auto',
 'leaf_size': 10,
 'n_neighbors': 21,
 'p': 1,
 'weights': 'distance'}

In [14]:
knn = KNeighborsClassifier(n_neighbors=21,weights='distance',algorithm='auto',leaf_size=10, p=1)

In [19]:
knn.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=10, n_neighbors=21, p=1, weights='distance')

In [20]:
knn.score(x_test,y_test)

0.6325

In [21]:
import pickle
pickle.dump(knn, open('knn.pkl', 'wb'))

In [22]:
pwd

'C:\\Users\\tarak\\OneDrive\\Desktop\\jupyter'

In [23]:
ls

 Volume in drive C is OS
 Volume Serial Number is 5CFF-620A

 Directory of C:\Users\tarak\OneDrive\Desktop\jupyter

11/29/2022  06:36 AM    <DIR>          .
11/29/2022  06:36 AM    <DIR>          ..
11/28/2022  08:01 PM    <DIR>          .ipynb_checkpoints
11/10/2022  07:44 AM             (540) admission_lr_model.pickle
11/24/2022  09:22 PM         4,697,789 AI4I 2020 Predictive Maintenance Dataset__Linear Regression.ipynb
11/10/2022  08:39 PM             (600) ai4i2020_maintainance__elastic_lr_model.pickle
11/10/2022  08:39 PM             (585) ai4i2020_maintainance__lasso_model.pickle
11/10/2022  08:39 PM             (492) ai4i2020_maintainance__lr_model.pickle
11/10/2022  08:39 PM             (499) ai4i2020_maintainance__ridge_lr_model.pickle
11/10/2022  11:05 PM          (22,578) CN numpy.ipynb
11/28/2022  08:01 PM        11,820,460 Decision Tree Final.ipynb
11/22/2022  07:56 PM      (11,140,212) Decision Tree.ipynb
11/22/2022  07:55 PM            48,904 dt_en_meta.dot
11/23/2022  

In [24]:
x_test

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
1508            7.1              0.27         0.60             2.1      0.074   
718             8.4              0.56         0.04             2.0      0.082   
1370            8.7              0.78         0.51             1.7      0.415   
579            10.6              0.31         0.49             2.2      0.063   
498            10.7              0.35         0.53             2.6      0.070   
...             ...               ...          ...             ...        ...   
1338            6.0              0.50         0.00             1.4      0.057   
860             7.2              0.62         0.06             2.7      0.077   
115             9.4              0.40         0.31             2.2      0.090   
1401            7.9              0.69         0.21             2.1      0.080   
585             7.6              0.51         0.24             2.4      0.091   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
1508                 17.0                  25.0  0.99814  3.38       0.72   
718                  10.0                  22.0  0.99760  3.22       0.44   
1370                 12.0                  66.0  0.99623  3.00       1.17   
579                  18.0                  40.0  0.99760  3.14       0.51   
498                   5.0                  16.0  0.99720  3.15       0.65   
...                   ...                   ...      ...   ...        ...   
1338                 15.0                  26.0  0.99448  3.36       0.45   
860                  15.0                  85.0  0.99746  3.51       0.54   
115                  13.0                  62.0  0.99660  3.07       0.63   
1401                 33.0                 141.0  0.99620  3.25       0.51   
585                   8.0                  38.0  0.99800  3.47       0.66   

      alcohol  
1508     10.6  
718       9.6  
1370      9.2  
579       9.8  
498      11.0  
...       ...  
1338      9.5  
860       9.5  
115      10.5  
1401      9.9  
585       9.6  

[400 rows x 11 columns]

In [25]:
x_test.iloc[0]

fixed acidity            7.10000
volatile acidity         0.27000
citric acid              0.60000
residual sugar           2.10000
chlorides                0.07400
free sulfur dioxide     17.00000
total sulfur dioxide    25.00000
density                  0.99814
pH                       3.38000
sulphates                0.72000
alcohol                 10.60000
Name: 1508, dtype: float64

In [26]:
knn.predict([x_test.iloc[0]])

C:\Users\tarak\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([6], dtype=int64)

## SVC

In [27]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [28]:
from sklearn.svm import SVC, SVR

In [29]:
svc = SVC()

In [30]:
svc.fit(x_train,y_train)

SVC()

In [31]:
svc.score(x_test,y_test)

0.5

In [32]:
param={
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'C' : [.1, .4, .6, 1, 2, 3, 100, 200, 500],
    'gamma':[.001,.1,.4,.004,.003]
}

In [33]:
svm_grid = GridSearchCV(svc, param_grid=param, verbose=3)

In [ ]:
svm_grid.fit(x_train,y_train)

Fitting 5 folds for each of 180 candidates, totalling 900 fits
[CV 1/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.600 total time=   0.2s
[CV 2/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.525 total time=   0.2s
[CV 3/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.575 total time=   0.1s
[CV 4/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.600 total time=   0.2s
[CV 5/5] END .C=0.1, gamma=0.001, kernel=linear;, score=0.548 total time=   0.3s
[CV 1/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.517 total time=   0.0s
[CV 2/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.500 total time=   0.0s
[CV 3/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.479 total time=   0.1s
[CV 4/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.483 total time=   0.0s
[CV 5/5] END ...C=0.1, gamma=0.001, kernel=poly;, score=0.510 total time=   0.0s
[CV 1/5] END ....C=0.1, gamma=0.001, kernel=rbf;, score=0.529 total time=   0.0s
[CV 2/5] END ....C=0.1, gamma=0.001, kernel=rb

In [ ]:
svm_grid.best_params_

In [34]:
svc1 = SVC(kernel='linear')

In [35]:
svc1.fit(x_train,y_train)

SVC(kernel='linear')

In [36]:
svc1.score(x_test,y_test)

0.5925

## SVR

In [37]:
data = pd.read_csv("E:\SVM\Admission_Prediction.csv")

In [38]:
data

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [39]:
data.isna().sum()

Serial No.            0
GRE Score            15
TOEFL Score          10
University Rating    15
SOP                   0
LOR                   0
CGPA                  0
Research              0
Chance of Admit       0
dtype: int64

In [40]:
data['GRE Score'] = data['GRE Score'].fillna(data['GRE Score'].mean())

In [41]:
data['TOEFL Score'] = data['TOEFL Score'].fillna(data['TOEFL Score'].mean())

In [42]:
data['University Rating'] = data['University Rating'].fillna(data['University Rating'].mean())

In [43]:
x=data.drop(columns=['Serial No.','Chance of Admit'])

In [44]:
x

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research
0    337.000000        118.0                4.0  4.5  4.5  9.65         1
1    324.000000        107.0                4.0  4.0  4.5  8.87         1
2    316.558763        104.0                3.0  3.0  3.5  8.00         1
3    322.000000        110.0                3.0  3.5  2.5  8.67         1
4    314.000000        103.0                2.0  2.0  3.0  8.21         0
..          ...          ...                ...  ...  ...   ...       ...
495  332.000000        108.0                5.0  4.5  4.0  9.02         1
496  337.000000        117.0                5.0  5.0  5.0  9.87         1
497  330.000000        120.0                5.0  4.5  5.0  9.56         1
498  312.000000        103.0                4.0  4.0  5.0  8.43         0
499  327.000000        113.0                4.0  4.5  4.5  9.04         0

[500 rows x 7 columns]

In [45]:
x.isna().sum()

GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
dtype: int64

In [46]:
y=data['Chance of Admit']

In [47]:
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [48]:
x_train, x_test, y_train, y_test = train_test_split(x,y, random_state=30, test_size=.20)

In [49]:
svr = SVR()

In [50]:
svr.fit(x_train,y_train)

SVR()

In [51]:
svr.score(x_test,y_test)

0.6774861142346673

In [52]:
from sklearn.metrics import r2_score

In [53]:
r2_score(y_test, svr.predict(x_test))

0.6774861142346673

In [54]:
svr.predict(x_test)

array([0.79688575, 0.56869993, 0.70213979, 0.63957666, 0.83300249,
       0.75707761, 0.65994706, 0.68822501, 0.73425829, 0.74644011,
       0.83586246, 0.68361861, 0.7742846 , 0.89252382, 0.81404201,
       0.82819776, 0.55198519, 0.60052276, 0.75981017, 0.71735058,
       0.70996637, 0.70163294, 0.79465708, 0.81204083, 0.77420576,
       0.56782111, 0.63432782, 0.68000782, 0.62334513, 0.58584246,
       0.6721899 , 0.54055777, 0.79251405, 0.64200758, 0.6673232 ,
       0.66244129, 0.6528857 , 0.79952426, 0.55052807, 0.662     ,
       0.57613553, 0.70849189, 0.68005545, 0.66963298, 0.78661726,
       0.6573585 , 0.92081692, 0.63184235, 0.62744472, 0.78123402,
       0.89119762, 0.69692383, 0.79749674, 0.69565313, 0.67689525,
       0.88664598, 0.63801105, 0.53762574, 0.62869004, 0.71534898,
       0.78286732, 0.68986065, 0.73407167, 0.64214697, 0.71423013,
       0.66859242, 0.66567013, 0.62528752, 0.86875038, 0.68531222,
       0.526498  , 0.87626977, 0.6520002 , 0.5400567 , 0.65004

In [55]:
svr.predict([x.iloc[0]])

C:\Users\tarak\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  warnings.warn(


array([0.89252382])

In [56]:
y[0]

0.92

## STACKING

In [57]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [58]:
df = pd.read_csv("E:\EnsembleLearning_And_RandomForest\EnsembleLearning_And_RandomForest\winequality_red.csv")

In [59]:
df

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [60]:
x=df.drop(columns='quality')

In [61]:
y=df.quality

In [68]:
train, val_train, test, val_test = train_test_split(x,y, test_size=.50, random_state=30)

In [69]:
x_train, x_test, y_train, y_test = train_test_split(train,test, random_state=30, test_size=.20)

In [70]:
knn = KNeighborsClassifier()

In [71]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [72]:
knn.score(x_test,y_test)

0.54375

In [73]:
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [74]:
svc.score(x_test,y_test)

0.4875

In [75]:
prediction_knn = knn.predict(val_train)
prediction_svc = svc.predict(val_train) 

In [76]:
prediction_knn

array([7, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 5, 6, 5, 5, 6,
       5, 5, 6, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 7, 6, 6, 5, 4,
       6, 7, 6, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5,
       6, 6, 5, 4, 5, 5, 5, 6, 6, 6, 7, 5, 5, 6, 6, 6, 7, 6, 5, 5, 5, 6,
       5, 5, 5, 7, 6, 7, 6, 7, 5, 6, 5, 5, 5, 6, 5, 7, 6, 5, 6, 5, 7, 5,
       5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5,
       5, 6, 7, 5, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 5, 5, 6, 7, 5, 5, 5, 5,
       6, 5, 6, 5, 4, 5, 5, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5,
       6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 6, 5, 7, 5, 6, 5,
       5, 6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 6, 6, 5, 6, 5, 4, 5, 6, 7, 5,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 6, 5, 6,
       6, 6, 5, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6, 5, 6, 6,
       5, 5, 6, 6, 6, 6, 5, 6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 6, 6, 5, 6, 6,
       7, 5, 6, 7, 5, 4, 6, 7, 5, 5, 6, 5, 5, 6, 5,

In [77]:
prediction_svc

array([6, 6, 6, 6, 6, 5, 6, 5, 5, 5, 6, 5, 6, 6, 5, 6, 6, 5, 6, 5, 6, 6,
       6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 5, 6, 5, 6, 6, 5, 5,
       6, 6, 5, 6, 5, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5, 6,
       5, 6, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 6, 5, 6, 5,
       5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 6, 6,
       6, 6, 6, 6, 6, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       5, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5,
       6, 6, 5, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 5, 6,
       6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 6,
       6, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 5, 6, 5,

In [80]:
input3 = np.column_stack((prediction_knn,prediction_svc))  #o/p: 1st col. for pred_knn and 2nd col. for pred_svc

In [84]:
pd.DataFrame(input3)

0  1
0    7  6
1    5  6
2    6  6
3    5  6
4    5  6
..  .. ..
795  5  6
796  5  6
797  5  6
798  6  6
799  5  5

[800 rows x 2 columns]

In [82]:
output = val_test

In [83]:
output

1147    7
659     4
871     5
1333    5
1411    6
       ..
1073    6
200     7
942     7
1106    6
1329    6
Name: quality, Length: 800, dtype: int64

In [87]:
rf = RandomForestClassifier()

In [88]:
rf.fit(input3,output)

RandomForestClassifier()

In [89]:
rf.score(x_test,y_test)  #it will not work because my train and test data are not same(X has 11 features, but RandomForestClassifier is expecting 2 features as input)

C:\Users\tarak\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(


ValueError: X has 11 features, but RandomForestClassifier is expecting 2 features as input.

In [ ]:
knn
svc
rf

In [90]:
knn_output = knn.predict(x_test)
svc_output = svc.predict(x_test)

In [92]:
output_stack1 = np.column_stack((knn_output,svc_output))

In [93]:
output_stack1

array([[5, 5],
       [6, 6],
       [5, 5],
       [5, 5],
       [6, 6],
       [6, 6],
       [5, 6],
       [6, 6],
       [6, 6],
       [5, 5],
       [6, 6],
       [5, 6],
       [5, 5],
       [5, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [5, 6],
       [5, 6],
       [6, 6],
       [5, 6],
       [7, 6],
       [6, 6],
       [5, 5],
       [6, 5],
       [5, 6],
       [7, 6],
       [5, 6],
       [5, 5],
       [5, 6],
       [6, 6],
       [5, 5],
       [6, 6],
       [5, 6],
       [6, 6],
       [6, 6],
       [5, 5],
       [5, 5],
       [6, 6],
       [5, 5],
       [5, 6],
       [6, 6],
       [5, 6],
       [5, 6],
       [6, 6],
       [7, 6],
       [5, 5],
       [5, 5],
       [6, 6],
       [5, 6],
       [6, 6],
       [5, 6],
       [6, 6],
       [5, 5],
       [5, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [6, 6],
       [5, 6],
       [5, 5],
       [5, 6],
       [5, 6],
       [7, 6],
       [6, 6],
       [5, 6],
       [5,

In [94]:
rf.predict(output_stack1)

array([5, 6, 5, 5, 6, 6, 5, 6, 6, 5, 6, 5, 5, 5, 6, 6, 6, 5, 5, 6, 5, 6,
       6, 5, 5, 5, 6, 5, 5, 5, 6, 5, 6, 5, 6, 6, 5, 5, 6, 5, 5, 6, 5, 5,
       6, 6, 5, 5, 6, 5, 6, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5, 5, 6, 6, 5,
       5, 5, 6, 5, 5, 5, 5, 6, 6, 6, 6, 5, 5, 5, 6, 6, 5, 6, 5, 6, 6, 5,
       6, 6, 5, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 6, 6, 5, 6, 5, 5, 6, 6, 5,
       5, 6, 6, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 6, 5,
       6, 6, 5, 6, 6, 5, 5, 6, 5, 5, 5, 6, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6,
       5, 5, 5, 6, 5, 5], dtype=int64)

In [95]:
rf.score(output_stack1 , y_test)

0.55